name: rich-codex
author: Phil Ewels

description: Create rich code images for your docs

branding:
  icon: "terminal"
  color: "yellow"

inputs:
  include:
    description: Files to search for rich-codex comments
    required: false
  exclude:
    description: Files to exclude from search for rich-codex comments
    required: false
  command:
    description: Command to run
    required: false
  snippet:
    description: Literal code snippet to render
    required: false
  img_paths:
    description: Path to image filenames if using 'command' or 'snippet'
    required: false
  configs:
    description: Paths to YAML config files
    default: |
      .rich_codex.yml
      .github/rich_codex.yml
    required: false
  width:
    description: Width of the terminal
    required: false
  theme:
    description: Colour theme
    required: false

# echo "::set-output name=<output name>::<value>"
outputs:
  images:
    description: JSON array of all generated images
  svgs:
    description: JSON array of all generated SVG files
  pngs:
    description: JSON array of all generated PNG files
  pdfs:
    description: JSON array of all generated PDF files

runs:
  using: "docker"
  image: Dockerfile
  env:
    SEARCH_INCLUDE: ${{ inputs.include }}
    SEARCH_EXCLUDE: ${{ inputs.exclude }}
    COMMAND: ${{ inputs.command }}
    SNIPPET: ${{ inputs.snippet }}
    IMG_PATHS: ${{ inputs.img_paths }}
    RC_CONFIGS: ${{ inputs.config }}
    TERMINAL_WIDTH: ${{ inputs.width }}
    TERMINAL_THEME: ${{ inputs.theme }}
