site_name: rich-codex
repo_name: ewels/rich-codex
repo_url: https://github.com/ewels/rich-codex

theme:
  name: material
  icon:
    logo: octicons/book-16
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  font:
    text: Noto Sans
  features:
    - navigation.instant

nav:
  - Home: index.md
  - Installation:
      - installation/github_action.md
      - installation/cli.md
      - installation/docker_image.md
  - Inputs:
      - inputs/markdown.md
      - inputs/direct_inputs.md
      - inputs/config_file.md
  - Configuration:
      - config/overview.md
      - config/time_limits.md
      - config/tweaks.md
      - config/command_setup.md
      - config/width.md
      - config/colours.md
      - config/cleaning.md
      - config/ignoring_changes.md
  - safety.md
  - troubleshooting.md

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
