site_name: rich-codex
theme:
  name: material
  icon:
    logo: octicons/book-16
  palette:
    scheme: slate
    primary: indigo
    accent: indigo
  features:
    - navigation.sections
nav:
  - Home: index.md
  - Installation:
      - installation/github_action.md
      - installation/cli.md
      - installation/docker_image.md
  - Inputs:
      - inputs/markdown.md
      - inputs/direct_inputs.md
      - inputs/config_file.md
  - Advanced:
      - advanced/ignoring_changes.md
      - advanced/safety.md
      - advanced/troubleshooting.md
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
