name: Basic example of terminal images using rich-codex
on: [push]
jobs:
  rich_codex:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Install your custom tools
        run: pip install cowsay lolcat

      - name: Generate terminal images with rich-codex
        uses: ewels/rich-codex@v1
        with:
          # This example runs in parallel to examples.yml, which will commit changes
          # So we don't mind if it finds changes - no need to exit with an error
          error_changes: "false"
