name: Build images / docs
on: [push]

jobs:
  rich_codex:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x

      - name: Install requirements for docs
        run: pip install cowsay lolcat mkdocs-material

      - name: Generate terminal images with rich-codex
        uses: ./ # Would normally be ewels/rich-codex@v1
        with:
          commit_changes: "true"
          clean_img_paths: docs/img/*.svg

      - name: Build and deploy docs
        run: mkdocs gh-deploy --force
