on: [push]

env:
  TERMINAL_WIDTH: 120
  FORCE_COLOR: true

jobs:
  markdown_comments:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install requirements
        run: pip install cowsay lolcat .

      - name: Generate images from markdown comments
        run: rich-codex

      - name: Add and commit new images
        run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email 'github-actions[bot]@users.noreply.github.com'
          if [[ `git status --porcelain` ]]; then
            git add . && git commit -m "Generate new screengrabs with rich-codex"
            git push
          fi

  actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install requirements
        run: pip install cowsay lolcat .

      - name: Generate images from actions commands
        run: rich-codex
        env:
          no_search: true
          width: 60
          command: cowsay "Taste the rainbow" | lolcat --force -S 100
          img_paths: |
            examples/actions/cowsay-colours.svg
            examples/actions/cowsay-colours.png
            examples/actions/cowsay-colours.pdf

      - name: Generate images from actions snippets
        run: rich-codex
        env:
          no_search: true
          snippet: |
            >>> print("[italic red]Hello[/italic red] World!", locals())
            Hello World!
            {
                '__annotations__': {},
                '__builtins__': <module 'builtins' (built-in)>,
                '__doc__': None,
                '__loader__': <class '_frozen_importlib.BuiltinImporter'>,
                '__name__': '__main__',
                '__package__': None,
                '__spec__': None,
                'print': <function print at 0x1027fd4c0>,
            }
          img_paths: |
            examples/actions/rich-example.svg
            examples/actions/rich-example.png
            examples/actions/rich-example.pdf

      - name: Add and commit new images
        run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email 'github-actions[bot]@users.noreply.github.com'
          if [[ `git status --porcelain` ]]; then
            git add . && git commit -m "Generate new screengrabs with rich-codex"
            git push
          fi
  yml_configs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install requirements
        run: pip install cowsay lolcat .

      - name: Generate images from a YAML config
        run: rich-codex
        env:
          no_search: true
          configs: yml_configs/*.yml

      - name: Add and commit new images
        run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email 'github-actions[bot]@users.noreply.github.com'
          if [[ `git status --porcelain` ]]; then
            git add . && git commit -m "Generate new screengrabs with rich-codex"
            git push
          fi
